export const scales = [
	{ name: "C Pentatonic", notes: ["C3", "D3", "E3", "G3", "A3"] },
	{ name: "C# Pentatonic", notes: ["C#3", "D#3", "F3", "G#3", "A#3"] },
	{ name: "D Pentatonic", notes: ["D3", "E3", "F#3", "A3", "B3"] },
	{ name: "Eb Pentatonic", notes: ["Eb3", "F3", "G3", "Bb3", "C4"] },
	{ name: "E Pentatonic", notes: ["E3", "F#3", "G#3", "B3", "C#4"] },
	{ name: "F Pentatonic", notes: ["F3", "G3", "A3", "C4", "D4"] },
	{ name: "F# Pentatonic", notes: ["F#3", "G#3", "A#3", "C#4", "D#4"] },
	{ name: "Gb Pentatonic", notes: ["Gb3", "Ab3", "Bb3", "Db4", "Eb4"] },
	{ name: "G Pentatonic", notes: ["G3", "A3", "B3", "D4", "E4"] },
	{ name: "Ab Pentatonic", notes: ["Ab3", "Bb3", "C4", "Eb4", "F4"] },
	{ name: "A Pentatonic", notes: ["A3", "B3", "C#4", "E4", "F#4"] },
	{ name: "Bb Pentatonic", notes: ["Bb3", "C4", "D4", "F4", "G4"] },
	{ name: "B Pentatonic", notes: ["B3", "C#4", "D#4", "F#4", "G#4"] },
];
